### ISSUE TITLE
Xiaomi Button (WXKG01LM)

### ISSUE THREAD

**Issue by Instanz1** [lasthead0/ioBroker.xiaomi-gateway3#7]
Sorry for my english, it's google translate :)

I use the above button, how can I provide you with data from it?

greeting

Instanz

**Comment by lasthead0** [comment]
Hi.
What is your language? We can switch to Russian if you want:) My English too not excellent :)
Yes, i work on it. You can turn on `Debug log` and `Lumi MQTT messages`, then press button, maybe several times. Look to ioBroker log and give me message for this device starts with `(_LUMI_) zigbee/send`. You can define message by `did` (something like this `"did":"lumi.158d00045fc9b3"`). Maybe you will have to look log from file becouse iob ui trim long messages.

**Comment by Instanz1** [comment]
Hello, my language would be German :)

I've looked through the logs and haven't found anything similar.

This is the excerpt from today's log, 5 minutes before I pressed the switch.

In the last few days, there has been nothing in the log from iobroker about xiaomi.

2022-01-22 08:43:16.978  - info: host.iobroker stopInstance system.adapter.xiaomi-gateway3.0 (force=false, process=true)
--
2022-01-22 08:43:17.022  - info: host.iobroker stopInstance system.adapter.xiaomi-gateway3.0 send kill signal
2022-01-22 08:43:17.021  - info: xiaomi-gateway3.0 (123512) Got terminate signal TERMINATE_YOURSELF
2022-01-22 08:43:17.041  - info: xiaomi-gateway3.0 (123512) terminating
2022-01-22 08:43:17.042  - info: xiaomi-gateway3.0 (123512) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2022-01-22 08:43:17.615  - info: host.iobroker instance system.adapter.xiaomi-gateway3.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
2022-01-22 08:43:20.094  - info: host.iobroker instance system.adapter.xiaomi-gateway3.0 started with pid 454385
2022-01-22 08:43:22.448  - info:  xiaomi-gateway3.0 (454385) starting. Version 0.3.0 in  /opt/iobroker/node_modules/iobroker.xiaomi-gateway3, node: v14.18.3,  js-controller: 3.3.22
2022-01-22 08:43:22.507  - info: xiaomi-gateway3.0 (454385) Xiaomi Gateway 3 adapter loaded.
2022-01-22 08:43:32.206  - info: xiaomi-gateway3.0 (454385) Xiaomi Gateway3 (192.168.178.88) firmware version = 1.5.1_0032

**Comment by lasthead0** [comment]
Did you enable logging like here?
![Снимок экрана 2022-01-22 в 12 27 47](https://user-images.githubusercontent.com/8353427/150633106-d3973f5d-b89e-4273-b791-17dffcc152ef.png)

Do you have other devices paired with this gateway?

**Comment by Instanz1** [comment]
Yes is activated.

No, that's currently the only device I've connected to it.

Just reinstalling my system and watching it again for a few days, as soon as there is something new I'll get back to you

**Comment by lasthead0** [comment]
Is object for this button was created in objects tree by adapter?
Also you can enable option `Debug output (to state)` and then give me value of `debug_output` state if there will be somesing.

**Comment by Instanz1** [comment]
Here I have now made the screens of everything that has to do with the adapter.
![Desktop Screenshot 2022 01 22 - 11 24 42 36](https://user-images.githubusercontent.com/77802286/150634874-afffe16a-1785-42dc-ae92-0ca3d4483b42.png)
![Desktop Screenshot 2022 01 22 - 11 25 08 65](https://user-images.githubusercontent.com/77802286/150634875-859efa4b-abd5-48b9-a3a6-97181c86b7f6.png)
![Desktop Screenshot 2022 01 22 - 11 25 37 28](https://user-images.githubusercontent.com/77802286/150634876-cb92530f-c7c4-4dc1-9348-497e5e8e799a.png)
![Desktop Screenshot 2022 01 22 - 11 26 45 21](https://user-images.githubusercontent.com/77802286/150634877-7f55fe00-7839-43ea-aa40-865f8936930b.png)

**Comment by lasthead0** [comment]
Oh. I guess i know what wrong. You should set `debug` level log for adapter. 
![Снимок экрана 2022-01-22 в 13 34 21](https://user-images.githubusercontent.com/8353427/150635113-a7a0b76a-8544-4ec0-9882-a95c2f191972.png)
I forgot to tell you about this.
I will add this info to README in future.

**Comment by Instanz1** [comment]
right now
![Desktop Screenshot 2022 01 22 - 12 00 32 23](https://user-images.githubusercontent.com/77802286/150635806-f46c7a75-7160-45ab-8884-2b68324e86cb.png)
?

**Comment by lasthead0** [comment]
Thx. That's all i need. I will try to add button state in a day or two. I will let you know here.

**Comment by lasthead0** [comment]
Hi.
I finally added buttons support. You can update/install adapter from iob `latest` repository or from `master` branch on git.
You should delete button object if it is exist to new object with necessary states will be created.

**Comment by Instanz1** [comment]
Thanks, I installed it yesterday, didn't have to delete it either, the data points were all newly created, the button is already in use and works!

thank you

**Comment by lasthead0** [comment]
Happy to hear that!
